version: '3.7'

services:
  #  docker run --name mysql -d --network host -v /cloud/downloads/mysql_docker/my.cnf:/etc/mysql/my.cnf -v /cloud/downloads/mysql_docker/log/:/var/log/mysql/ -v /cloud/downloads/mysql_docker/lib/:/var/lib/mysql/ -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER='kodi' -e MYSQL_PASSWORD='kodi' --restart=always hypriot/rpi-mysql
  rpi_mysql:
    image: 'hypriot/rpi-mysql'
    container_name: 'rpi-mysql'
    ports:
      - '3306:3306'
    volumes:
      - /cloud/downloads/mysql_docker/my.cnf:/etc/mysql/my.cnf
      - /cloud/downloads/mysql_docker/log/:/var/log/mysql/
      - /cloud/downloads/mysql_docker/lib/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'kodi'
      MYSQL_PASSWORD: 'kodi'
      MYSQL_ROOT_PASSWORD: 'root'
    network_mode: host
    deploy:
      restart_policy:
        condition: always
  # docker run --name sherpa -d network host -v /cloud/torrents/:/usr/src/app/data/torrents -v /cloud/downloads/ready/:/usr/src/app/data/downloads -v /cloud/series/tv_series/:/usr/src/app/data/tv_shows -v /home/pi/sherpa/series.yml:/usr/src/app/data/settings/series.yml -e RAILS_ENV=production -e LEVEL_LOG=debug -e LOGS_TO_STDOUT=1 -e DB_NAME=sherpa --restart=always ga6ix/sherpa
  rpi_sherpa:
    image: 'ga6ix/sherpa'
    container_name: 'sherpa'
    volumes:
      - /cloud/torrents/:/usr/src/app/data/torrents
      - /cloud/downloads/ready/:/usr/src/app/data/downloads
      - /cloud/series/tv_series/:/usr/src/app/data/tv_shows
      - /home/pi/sherpa/series.yml:/usr/src/app/data/settings/series.yml
    environment:
      RAILS_ENV: production 
      LEVEL_LOG: debug
      LOGS_TO_STDOUT: 1
      DB_HOST: rpi_mysql
      DB_PORT: 3306
      DB_NAME: sherpa
      DB_USER: root
      DB_PASS: root
    depends_on:
      - rpi_mysql
  # docker run --name rpi sherpa -d network host -v /cloud/torrents/:/usr/src/app/data/torrents -v /cloud/downloads/ready/:/usr/src/app/data/downloads -v /cloud/series/tv_series/:/usr/src/app/data/tv_shows -v /home/pi/sherpa/series.yml:/usr/src/app/data/settings/series.yml -e RAILS_ENV=production -e LEVEL_LOG=debug -e LOGS_TO_STDOUT=1 -e DB_NAME=sherpa --restart=always -c "rails db:create db:migrate" ga6ix/sherpa
  rpi_sherpa_migrator:
    image: 'ga6ix/sherpa'
    container_name: 'sherpa'
    volumes:
      - /cloud/torrents/:/usr/src/app/data/torrents
      - /cloud/downloads/ready/:/usr/src/app/data/downloads
      - /cloud/series/tv_series/:/usr/src/app/data/tv_shows
      - /home/pi/sherpa/series.yml:/usr/src/app/data/settings/series.yml
    environment:
      RAILS_ENV: production 
      LEVEL_LOG: debug
      LOGS_TO_STDOUT: 1
      DB_HOST: rpi_mysql
      DB_PORT: 3306
      DB_NAME: sherpa
      DB_USER: root
      DB_PASS: root
    command: 'rails db:create db:migrate'
    depends_on:
      - rpi_mysql  
  # docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 mysql
  mysql:
    image: 'mysql:5.7'
    container_name: 'mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
  # docker run --name sherpa -d network host -v /home/ga6ix/src/sherpa/data/torrents/:/usr/src/app/data/torrents -v /home/ga6ix/src/sherpa/data/downloads/:/usr/src/app/data/downloads -v /home/ga6ix/src/sherpa/data/tv_shows/:/usr/src/app/data/tv_shows -v /home/ga6ix/src/sherpa/data/settings/series.yml:/usr/src/app/data/settings/series.yml -e RAILS_ENV=production -e LEVEL_LOG=debug -e LOGS_TO_STDOUT=1 -e DB_NAME=sherpa --restart=always ga6ix/sherpa
  sherpa:
    image: 'ga6ix/sherpa'
    container_name: 'sherpa'
    volumes:
      - /home/ga6ix/src/sherpa/data/torrents/:/usr/src/app/data/torrents
      - /home/ga6ix/src/sherpa/data/downloads/:/usr/src/app/data/downloads
      - /home/ga6ix/src/sherpa/data/tv_shows/:/usr/src/app/data/tv_shows
      - /home/ga6ix/src/sherpa/data/settings/series.yml:/usr/src/app/data/settings/series.yml
    environment:
      RAILS_ENV: production
      LEVEL_LOG: debug
      LOGS_TO_STDOUT: 1
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: sherpa
      DB_USER: root
      DB_PASS: root
    # depends_on:
    #   - mysql
  # docker run --name sherpa -d network host -v /home/ga6ix/src/sherpa/data/torrents/:/usr/src/app/data/torrents -v /home/ga6ix/src/sherpa/data/downloads/:/usr/src/app/data/downloads -v /home/ga6ix/src/sherpa/data/tv_shows/:/usr/src/app/data/tv_shows -v /home/ga6ix/src/sherpa/data/settings/series.yml:/usr/src/app/data/settings/series.yml -e RAILS_ENV=production -e LEVEL_LOG=debug -e LOGS_TO_STDOUT=1 -e DB_NAME=sherpa --restart=always -c "rails db:create db:migrate" ga6ix/sherpa
  sherpa_migrator:
    image: 'sherpa'
    container_name: 'sherpa'
    depends_on:
      - mysql
    volumes:
      - /home/ga6ix/src/sherpa/data/torrents/:/usr/src/app/data/torrents
      - /home/ga6ix/src/sherpa/data/downloads/:/usr/src/app/data/downloads
      - /home/ga6ix/src/sherpa/data/tv_shows/:/usr/src/app/data/tv_shows
      - /home/ga6ix/src/sherpa/data/settings/series.yml:/usr/src/app/data/settings/series.yml
    environment:
      RAILS_ENV: production
      LEVEL_LOG: debug
      LOGS_TO_STDOUT: 1
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: sherpa
      DB_USER: root
      DB_PASS: root
    command: 'rails db:create db:migrate'
