db_defaults: &db_defaults
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  reconnect: false
  pool: 20
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *db_defaults

production:
  <<: *db_defaults

test:
  <<: *db_defaults
  database: <%= ENV.fetch('DB_NAME', 'core') + '_test' %>
